<?php

if (!defined('ABSPATH')) {
    exit;
}

$lib = array(
    'normalize' => array(
        'type' => 'style',
        'title' => __('Normalize.css','libraries'),
        'src' => 'stylesheets/normalize.css',
        'ver' => '4.1.1c',
        'depend' => array(),
    ),
    'justbenice' => array(
        'type' => 'style',
        'title' => __('Justbenice.css','libraries'),
        'description' => __('CSS grid from bootstrap 4 + styles needed for owlCarousel.', 'libraries'),
        'src' => 'stylesheets/justbenice.css',
        'ver' => '1.0.1',
        'depend' => array('normalize'),
    ),
    'modernizr' => array(
        'type' => 'script',
        'title' => __('Modernizr.js','libraries'),
        'description' => __("Let's learn that HTML5 and CSS3 are user-friendly", 'libraries'),
        'link' => 'https://modernizr.com/',
        'src' => 'javascripts/modernizr.min.js',
        'ver' => '2.8.3',
        'depend' => array(),
    ),
    'prefixfree' => array(
        'type' => 'script',
        'title' => __('Prefixfree.js','libraries'),
        'description' => __('Eliminating the need to specify prefixes in styles.', 'libraries'),
        'link' => 'https://leaverou.github.io/prefixfree/',
        'src' => 'javascripts/prefixfree.min.js',
        'ver' => '1.0.7',
        'depend' => array(),
    ),
    'pace' => array(
        'type' => 'script',
        'title' => __('Pace.js','libraries'),
        'description' => __('Automatic page loading indicator for the site with tracking of ajax-requests and the status of page loading (readyState).', 'libraries'),
        'link' => 'http://github.hubspot.com/pace/docs/welcome/',
        'src' => 'javascripts/pace.min.js',
        'ver' => '1.0.0',
        'depend' => array(),
    ),
    'jquerymask' => array(
        'type' => 'script',
        'title' => __('jQueryMask.js','libraries'),
        'description' => __('Allows masking text input field.', 'libraries'),
        'link' => 'http://blog.igorescobar.com',
        'src' => 'javascripts/jquery/jquery.mask.js',
        'ver' => '1.14.11',
        'depend' => array('jquery'),
    ),
    'lazy' => array(
        'type' => 'script',
        'title' => __('Lazy.js','libraries'),
        'description' => __('Library for progressive loading of images.', 'libraries'),
        'link' => 'http://jquery.eisbehr.de/lazy/',
        'src' => 'javascripts/jquery/jquery.lazy.min.js',
        'ver' => '1.7.5',
        'depend' => array('jquery'),
    ),
    'isotope' => array(
        'type' => 'script',
        'title' => __('Isotope.js','libraries'),
        'description' => __('A library for building blocks of different sizes one after another both horizontally and vertically with no spaces.', 'libraries'),
        'link' => 'http://isotope.metafizzy.co',
        'src' => 'javascripts/jquery/isotope.pkgd.min.js',
        'ver' => '3.0.1',
        'depend' => array('jquery'),
    ),
    'isotope_masonry' => array(
        'type' => 'script',
        'title' => __('Masonry layout for isotope','libraries'),
        'description' => __('Additional library to Isotope.js with the system of objects location.', 'libraries'),
        'link' => 'http://isotope.metafizzy.co',
        'src' => 'javascripts/jquery/isotope.masonryHorizontal.pkgd.min.js',
        'ver' => '2.0.0',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_cellsbyrow' => array(
        'type' => 'script',
        'title' => __('cellsByRows','libraries'),
        'description' => __('cellsByRows layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/cellsbyrow.html',
        'src' => 'javascripts/jquery/isotope.cells-by-row.js',
        'ver' => '1.1.3',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_cellsbycolumn' => array(
        'type' => 'script',
        'title' => __('cellsByColumns','libraries'),
        'description' => __('cellsByColumn layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/cellsbycolumn.html',
        'src' => 'javascripts/jquery/isotope.cells-by-column.js',
        'ver' => '1.1.3',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_fitcolumns' => array(
        'type' => 'script',
        'title' => __('fitColumns','libraries'),
        'description' => __('fitColumns layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/fitcolumns.html',
        'src' => 'javascripts/jquery/isotope.fit-columns.js',
        'ver' => '1.1.3',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_horizontal' => array(
        'type' => 'script',
        'title' => __('horizontal','libraries'),
        'description' => __('horizontal layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/horiz.html',
        'src' => 'javascripts/jquery/isotope.horizontal.js',
        'ver' => '2.0.0',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_packery' => array(
        'type' => 'script',
        'title' => __('packery','libraries'),
        'description' => __('', 'libraries'),
        'src' => 'javascripts/jquery/isotope.packery-mode.pkgd.min.js',
        'ver' => '2.0.0',
        'depend' => array('jquery','isotope'),
    ),
    'stretchclass' => array(
        'type' => 'script',
        'title' => __('stretchClass.js','libraries'),
        'description' => __('Alpha version of the library, which sets the width of the images to 100%, and the height of the auto. <br/> It takes into account the maximum width of the image from the width attribute, and if it is not set loads naturalWidth with ImagesLoaded.js', 'libraries'),
        'src' => 'javascripts/jquery/jquery.stretchclass.js',
        'ver' => '0.0.2a',
        'depend' => array('jquery','imagesloaded'),
    ),
    'fullscreenclass' => array(
        'type' => 'script',
        'title' => __('fullScreenClass.js ','libraries'),
        'description' => __("The Alpha version of the library, operates by opening windows on top of everything based on styles and allows an additional function of the window's properties.", 'libraries'),
        'src' => 'javascripts/jquery/jquery.fullscreenclass.js',
        'ver' => '0.0.1a',
        'depend' => array('jquery'),
    ),
    'owlcarousel' => array(
        'type' => 'script',
        'title' => __('owlCarousel.js','libraries'),
        'description' => __('Slider for images.', 'libraries'),
        'link' => 'https://owlcarousel2.github.io/OwlCarousel2/',
        'src' => 'javascripts/jquery/owl.carousel.min.js',
        'ver' => 'v2.0.0-beta.2.4',
        'depend' => array('jquery'),
    ),
    'animate' => array(
        'type' => 'style',
        'title' => __('animate.css','libraries'),
        'description' => __('The animation styles used by owlCarousel (can be used separately).', 'libraries'),
        'link' => 'https://daneden.github.io/animate.css/',
        'src' => 'stylesheets/animate.css',
        'ver' => '2.0.0',
        'depend' => array(),
    ),
    'google_clustermarkers' => array(
        'type' => 'script',
        'title' => __('GoogleClusterMarkers.js','libraries'),
        'description' => __('A library that allows you to group markers on a map.', 'libraries'),
        'link' => 'https://github.com/googlemaps/js-marker-clusterer',
        'src' => 'javascripts/google/markerclusterer.min.js',
        'ver' => '1.0.0',
        'depend' => array('jquery','google-map'),

    ),
    'google_infobubble' => array(
        'type' => 'script',
        'title' => __('GoogleInfoBubble.js','libraries'),
        'description' => __('Pop-ups when clicking on the marker.', 'libraries'),
        'link' => 'https://github.com/googlemaps/js-info-bubble',
        'src' => 'javascripts/google/infobubble.min.js',
        'ver' => '0.8.0',
        'depend' => array('jquery','google-map'),
    ),
    'fullpage' => array(
        'type' => 'script',
        'title' => __('Fullpage.js','libraries'),
        'description' => __('Allows you to scroll page.', 'libraries'),
        'link' => 'https://github.com/alvarotrigo/fullPage.js',
        'src' => 'javascripts/jquery/jquery.fullpage.min.js',
        'ver' => '2.9.2',
        'depend' => array('jquery'),
    ),
    'fullpage_scrolloverflow' => array(
        'type' => 'script',
        'title' => __('Scrolloverflow.min.js','libraries'),
        'description' => __('Scrolls everything that overflows in fullPage', 'libraries'),
        'src' => 'javascripts/jquery/scrolloverflow.min.js',
        'ver' => '5.2.0',
        'depend' => array('jquery'),
    ),
    'jquery_ui_touch_punch' => array(
        'type' => 'script',
        'title' => __('jQuery UI Touch Punch','libraries'),
        'description' => __('Allows to drag manipulate elements on touch screens', 'libraries'),
        'src' => 'javascripts/jquery/jquery.ui.touch-punch.min.js',
        'ver' => '0.2.3',
        'depend' => array('jquery','jquery-ui-core','jquery-ui-widget','jquery-ui-mouse'),
    ),
    'jquery-ui-core' => array(
        'type' => 'script',
        'title' => __('UI core','libraries'),
        'description' => __('jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top of the jQuery JavaScript Library.','libraries'),
        'link' => 'http://jqueryui.com/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-draggable' => array(
        'type' => 'script',
        'title' => __('Draggable','libraries'),
        'description' => __('Allow elements to be moved using the mouse.','libraries'),
        'link' => 'http://jqueryui.com/demos/draggable/',
        'depend' => array('jquery, jquery-ui-core'),
    ),
    'jquery-ui-droppable' => array(
        'type' => 'script',
        'title' => __('Droppable','libraries'),
        'description' => __('Create targets for draggable elements','libraries'),
        'link' => 'http://jqueryui.com/demos/droppable/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-resizable' => array(
        'type' => 'script',
        'title' => __('Resizable','libraries'),
        'description' => __('Change the size of an element using the mouse.','libraries'),
        'link' => 'http://jqueryui.com/demos/resizable/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-selectable' => array(
        'type' => 'script',
        'title' => __('Selectable','libraries'),
        'description' => __('Use the mouse to select elements, individually or in a group.','libraries'),
        'link' => 'http://jqueryui.com/demos/selectable/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-sortable' => array(
        'type' => 'script',
        'title' => __('Sortable','libraries'),
        'description' => __('Reorder elements in a list or grid using the mouse.','libraries'),
        'link' => 'http://jqueryui.com/demos/sortable/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-accordion' => array(
        'type' => 'script',
        'title' => __('Accordion','libraries'),
        'description' => __('Displays collapsible content panels for presenting information in a limited amount of space.','libraries'),
        'link' => 'http://jqueryui.com/demos/accordion/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-autocomplete' => array(
        'type' => 'script',
        'title' => __('Autocomplete','libraries'),
        'description' => __('Enables users to quickly find and select from a pre-populated list of values as they type, leveraging searching and filtering.','libraries'),
        'link' => 'http://jqueryui.com/demos/autocomplete/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-button' => array(
        'type' => 'script',
        'title' => __('Button','libraries'),
        'description' => __('Enhances standard form elements like buttons, inputs and anchors to themeable buttons with appropriate hover and active styles.','libraries'),
        'link' => 'http://jqueryui.com/demos/button/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-datepicker' => array(
        'type' => 'script',
        'title' => __('Datepicker','libraries'),
        'description' => __('Select a date from a popup or inline calendar','libraries'),
        'link' => 'http://jqueryui.com/demos/datepicker/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-dialog' => array(
        'type' => 'script',
        'title' => __('Dialog','libraries'),
        'description' => __('Open content in an interactive overlay.','libraries'),
        'link' => 'http://jqueryui.com/demos/dialog/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-menu' => array(
        'type' => 'script',
        'title' => __('Menu','libraries'),
        'description' => __('Themeable menu with mouse and keyboard interactions for navigation.','libraries'),
        'link' => 'http://jqueryui.com/menu/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-progressbar' => array(
        'type' => 'script',
        'title' => __('Progressbar','libraries'),
        'description' => __('Display status of a determinate or indeterminate process.','libraries'),
        'link' => 'http://jqueryui.com/demos/progressbar/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-selectmenu' => array(
        'type' => 'script',
        'title' => __('Selectmenu','libraries'),
        'description' => __('Duplicates and extends the functionality of a native HTML select element to overcome the limitations of the native control.','libraries'),
        'link' => 'http://jqueryui.com/selectmenu/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-slider' => array(
        'type' => 'script',
        'title' => __('Slider','libraries'),
        'description' => __('Drag a handle to select a numeric value.','libraries'),
        'link' => 'http://jqueryui.com/demos/slider/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-spinner' => array(
        'type' => 'script',
        'title' => __('Spinner','libraries'),
        'description' => __('Enhance a text input for entering numeric values, with up/down buttons and arrow key handling.','libraries'),
        'link' => 'http://jqueryui.com/demos/spinner/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-tabs' => array(
        'type' => 'script',
        'title' => __('Tabs','libraries'),
        'description' => __('A single content area with multiple panels, each associated with a header in a list.','libraries'),
        'link' => 'http://jqueryui.com/demos/tabs/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-tooltip' => array(
        'type' => 'script',
        'title' => __('Tooltips','libraries'),
        'description' => __('Customizable, themeable tooltips, replacing native tooltips.','libraries'),
        'link' => 'http://jqueryui.com/demos/tooltip/'
    ),
    'jquery-ui-widget' => array(
        'type' => 'script',
        'title' => __('Widget','libraries'),
        'description' => __('Create stateful jQuery plugins using the same abstraction as all jQuery UI widgets.','libraries'),
        'link' => 'http://jqueryui.com/widget/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-position' => array(
        'type' => 'script',
        'title' => __('Position','libraries'),
        'description' => __('Position an element relative to the window, document, another element, or the cursor/mouse.','libraries'),
        'link' => 'http://jqueryui.com/demos/position/',
        'depend' => array('jquery'),
    ),
    'jquery-ui-mouse' => array(
        'type' => 'script',
        'title' => __('Mouse','libraries'),
        'description' => __('Mouse Interaction','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-core' => array(
        'type' => 'script',
        'title' => __('Effects core','libraries'),
        'description' => __('Apply an animation effect to an element.','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-blind' => array(
        'type' => 'script',
        'title' => __('Blind','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-bounce' => array(
        'type' => 'script',
        'title' => __('Bounce','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-clip' => array(
        'type' => 'script',
        'title' => __('Clip','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-drop' => array(
        'type' => 'script',
        'title' => __('Drop','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-explode' => array(
        'type' => 'script',
        'title' => __('Explode','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-fade' => array(
        'type' => 'script',
        'title' => __('Fade','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-fold' => array(
        'type' => 'script',
        'title' => __('Fold','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-highlight' => array(
        'type' => 'script',
        'title' => __('Highlight','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-pulsate' => array(
        'type' => 'script',
        'title' => __('Pulsate','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-scale' => array(
        'type' => 'script',
        'title' => __('Scale','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-shake' => array(
        'type' => 'script',
        'title' => __('Shake','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-slide' => array(
        'type' => 'script',
        'title' => __('Slide','libraries'),
        'depend' => array('jquery'),
    ),
    'jquery-effects-transfer' => array(
        'type' => 'script',
        'title' => __('Transfer','libraries'),
        'depend' => array('jquery'),
    ),

);
