<?php

if (!defined('ABSPATH')) {
    exit;
}

$lib = array(
    'normalize' => array(
        'type' => 'style',
        'name' => 'normalize',
        'title' => 'Normalize.css',
        'src' => 'stylesheets/normalize.css',
        'ver' => '4.1.1c',
        'depend' => array(),
    ),
    'justbenice' => array(
        'type' => 'style',
        'name' => 'justbenice',
        'title' => 'Justbenice.css',
        'description' => __('CSS grid from bootstrap 4 + styles needed for owlCarousel.', 'libraries'),
        'src' => 'stylesheets/justbenice.css',
        'ver' => '1.0.1',
        'depend' => array('normalize'),
    ),
    'modernizr' => array(
        'type' => 'script',
        'name' => 'modernizr',
        'title' => 'Modernizr.js',
        'description' => __("Let's learn that HTML5 and CSS3 are user-friendly", 'libraries'),
        'link' => 'https://modernizr.com/',
        'src' => 'javascripts/modernizr.min.js',
        'ver' => '2.8.3',
        'depend' => array(),
    ),
    'prefixfree' => array(
        'type' => 'script',
        'name' => 'prefixfree',
        'title' => 'Prefixfree.js',
        'description' => __('Eliminating the need to specify prefixes in styles.', 'libraries'),
        'link' => 'https://leaverou.github.io/prefixfree/',
        'src' => 'javascripts/prefixfree.min.js',
        'ver' => '1.0.7',
        'depend' => array(),
    ),
    'pace' => array(
        'type' => 'script',
        'name' => 'pace',
        'title' => 'Pace.js',
        'description' => __('Automatic page loading indicator for the site with tracking of ajax-requests and the status of page loading (readyState).', 'libraries'),
        'link' => 'http://github.hubspot.com/pace/docs/welcome/',
        'src' => 'javascripts/pace.min.js',
        'ver' => '1.0.0',
        'depend' => array(),
    ),
    'jquerymask' => array(
        'type' => 'script',
        'name' => 'jquerymask',
        'title' => 'jQueryMask.js',
        'description' => __('Allows masking text input field.', 'libraries'),
        'link' => 'http://blog.igorescobar.com',
        'src' => 'javascripts/jquery/jquery.mask.js',
        'ver' => '1.14.11',
        'depend' => array('jquery'),
    ),
    'lazy' => array(
        'type' => 'script',
        'name' => 'lazy',
        'title' => 'Lazy.js',
        'description' => __('Library for progressive loading of images.', 'libraries'),
        'link' => 'http://jquery.eisbehr.de/lazy/',
        'src' => 'javascripts/jquery/jquery.lazy.min.js',
        'ver' => '1.7.5',
        'depend' => array('jquery'),
    ),
    'isotope' => array(
        'type' => 'script',
        'name' => 'isotope',
        'title' => 'Isotope.js',
        'description' => __('A library for building blocks of different sizes one after another both horizontally and vertically with no spaces.', 'libraries'),
        'link' => 'http://isotope.metafizzy.co',
        'src' => 'javascripts/jquery/isotope.pkgd.min.js',
        'ver' => '3.0.1',
        'depend' => array('jquery'),
    ),
    'isotope_masonry' => array(
        'type' => 'script',
        'name' => 'isotope_masonry',
        'title' => 'Masonry layout for isotope',
        'description' => __('Additional library to Isotope.js with the system of objects location.', 'libraries'),
        'link' => 'http://isotope.metafizzy.co',
        'src' => 'javascripts/jquery/isotope.masonryHorizontal.pkgd.min.js',
        'ver' => '2.0.0',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_cellsbyrow' => array(
        'type' => 'script',
        'name' => 'isotope_cellsbyrow',
        'title' => 'cellsByRows',
        'description' => __('cellsByRows layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/cellsbyrow.html',
        'src' => 'javascripts/jquery/isotope.cells-by-row.js',
        'ver' => '1.1.3',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_cellsbycolumn' => array(
        'type' => 'script',
        'name' => 'isotope_cellsbycolumn',
        'title' => 'cellsByColumns',
        'description' => __('cellsByColumn layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/cellsbycolumn.html',
        'src' => 'javascripts/jquery/isotope.cells-by-column.js',
        'ver' => '1.1.3',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_fitcolumns' => array(
        'type' => 'script',
        'name' => 'isotope_fitcolumns',
        'title' => 'fitColumns',
        'description' => __('fitColumns layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/fitcolumns.html',
        'src' => 'javascripts/jquery/isotope.fit-columns.js',
        'ver' => '1.1.3',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_horizontal' => array(
        'type' => 'script',
        'name' => 'isotope_horizontal',
        'title' => 'horizontal',
        'description' => __('horizontal layout mode for Isotope', 'libraries'),
        'link' => 'http://isotope.metafizzy.co/layout-modes/horiz.html',
        'src' => 'javascripts/jquery/isotope.horizontal.js',
        'ver' => '2.0.0',
        'depend' => array('jquery','isotope'),
    ),
    'isotope_packery' => array(
        'type' => 'script',
        'name' => 'isotope_packery',
        'title' => 'packery',
        'description' => __('', 'libraries'),
        'src' => 'javascripts/jquery/isotope.packery-mode.pkgd.min.js',
        'ver' => '2.0.0',
        'depend' => array('jquery','isotope'),
    ),
    'aspectratio' => array(
        'type' => 'script',
        'name' => 'aspectratio',
        'title' => 'aspectRatio.js',
        'description' => __('Alpha version of the library to preserve the aspect ratio for objects.', 'libraries'),
        'src' => 'javascripts/jquery/jquery.aspectratio.js',
        'ver' => '0.0.2a',
        'depend' => array('jquery'),
    ),
    'stretchclass' => array(
        'type' => 'script',
        'name' => 'stretchclass',
        'title' => 'stretchClass.js',
        'description' => __('Alpha version of the library, which sets the width of the images to 100%, and the height of the auto. <br/> It takes into account the maximum width of the image from the width attribute, and if it is not set loads naturalWidth with ImagesLoaded.js', 'libraries'),
        'src' => 'javascripts/jquery/jquery.stretchclass.js',
        'ver' => '0.0.2a',
        'depend' => array('jquery','imagesloaded'),
    ),
    'fullscreenclass' => array(
        'type' => 'script',
        'name' => 'fullscreenclass',
        'title' => 'fullScreenClass.js ',
        'description' => __("The Alpha version of the library, operates by opening windows on top of everything based on styles and allows an additional function of the window's properties.", 'libraries'),
        'src' => 'javascripts/jquery/jquery.fullscreenclass.js',
        'ver' => '0.0.1a',
        'depend' => array('jquery'),
    ),
    'owlcarousel' => array(
        'type' => 'script',
        'name' => 'owlcarousel',
        'title' => 'owlCarousel.js',
        'description' => __('Slider for images.', 'libraries'),
        'link' => 'https://owlcarousel2.github.io/OwlCarousel2/',
        'src' => 'javascripts/jquery/owl.carousel.min.js',
        'ver' => 'v2.0.0-beta.2.4',
        'depend' => array('jquery'),
    ),
    'animate' => array(
        'type' => 'style',
        'name' => 'animate',
        'title' => 'animate.css',
        'description' => __('The animation styles used by owlCarousel (can be used separately).', 'libraries'),
        'link' => 'https://daneden.github.io/animate.css/',
        'src' => 'stylesheets/animate.css',
        'ver' => '2.0.0',
        'depend' => array(),
    ),
    'google_clustermarkers' => array(
        'type' => 'script',
        'name' => 'google_clustermarkers',
        'title' => 'GoogleClusterMarkers.js',
        'description' => __('A library that allows you to group markers on a map.', 'libraries'),
        'link' => 'https://github.com/googlemaps/js-marker-clusterer',
        'src' => 'javascripts/google/markerclusterer.min.js',
        'ver' => '1.0.0',
        'depend' => array('jquery','google-map'),

    ),
    'google_infobubble' => array(
        'type' => 'script',
        'name' => 'google_infobubble',
        'title' => 'GoogleInfoBubble.js',
        'description' => __('Pop-ups when clicking on the marker.', 'libraries'),
        'link' => 'https://github.com/googlemaps/js-info-bubble',
        'src' => 'javascripts/google/infobubble.min.js',
        'ver' => '0.8.0',
        'depend' => array('jquery','google-map'),
    ),
    'fullpage' => array(
        'type' => 'script',
        'name' => 'fullpage',
        'title' => 'Fullpage.js',
        'description' => __('Allows you to scroll page.', 'libraries'),
        'link' => 'https://github.com/alvarotrigo/fullPage.js',
        'src' => 'javascripts/jquery/jquery.fullpage.min.js',
        'ver' => '2.9.2',
        'depend' => array('jquery'),
    ),
    'fullpage_scrolloverflow' => array(
        'type' => 'script',
        'name' => 'fullpage_scrolloverflow',
        'title' => 'Scrolloverflow.min.js',
        'description' => __('Scrolls everything that overflows in fullPage', 'libraries'),
        'src' => 'javascripts/jquery/scrolloverflow.min.js',
        'ver' => '5.2.0',
        'depend' => array('jquery'),
    ),
    'jquery_ui_touch_punch' => array(
        'type' => 'script',
        'name' => 'jquery_ui_touch_punch',
        'title' => 'jQuery UI Touch Punch',
        'description' => __('Allows to drag manipulate elements on touch screens', 'libraries'),
        'src' => 'javascripts/jquery/jquery.ui.touch-punch.min.js',
        'ver' => '0.2.3',
        'depend' => array('jquery','jquery-ui-core','jquery-ui-widget','jquery-ui-mouse'),
    ),

    'jquery_ui_touch_punch' => array(
        'type' => 'script',
        'name' => 'jquery_ui_touch_punch',
        'title' => 'jQuery UI Touch Punch',
        'description' => __('Allows to drag manipulate elements on touch screens', 'libraries'),
        'src' => 'javascripts/jquery/jquery.ui.touch-punch.min.js',
        'ver' => '0.2.3',
        'depend' => array('jquery','jquery-ui-core','jquery-ui-widget','jquery-ui-mouse'),
    ),

    'jquery-ui-draggable' => array(
		'name' => 'Draggable',
		'slug' => 'jquery-ui-draggable',
		'info' => 'Allow elements to be moved using the mouse.',
		'link' => 'http://jqueryui.com/demos/draggable/'
	),
    'jquery-ui-droppable' => array(
		'name' => 'Droppable',
		'slug' => 'jquery-ui-droppable',
		'info' => 'Create targets for draggable elements',
		'link' => 'http://jqueryui.com/demos/droppable/'
	),
    'jquery-ui-resizable' => array(
		'name' => 'Resizable',
		'slug' => 'jquery-ui-resizable',
		'info' => 'Change the size of an element using the mouse.',
		'link' => 'http://jqueryui.com/demos/resizable/'
	),
    'jquery-ui-selectable' => array(
		'name' => 'Selectable',
		'slug' => 'jquery-ui-selectable',
		'info' => 'Use the mouse to select elements, individually or in a group.',
		'link' => 'http://jqueryui.com/demos/selectable/'
	),
    'jquery-ui-sortable' => array(
		'name' => 'Sortable',
		'slug' => 'jquery-ui-sortable',
		'info' => 'Reorder elements in a list or grid using the mouse.',
		'link' => 'http://jqueryui.com/demos/sortable/'
	),
    'jquery-ui-accordion' => array(
		'name' => 'Accordion',
		'slug' => 'jquery-ui-accordion',
		'info' => 'Displays collapsible content panels for presenting information in a limited amount of space.',
		'link' => 'http://jqueryui.com/demos/accordion/'
	),
    'jquery-ui-autocomplete' => array(
		'name' => 'Autocomplete',
		'slug' => 'jquery-ui-autocomplete',
		'info' => 'Enables users to quickly find and select from a pre-populated list of values as they type, leveraging searching and filtering.',
		'link' => 'http://jqueryui.com/demos/autocomplete/'
	),
    'jquery-ui-button' => array(
		'name' => 'Button',
		'slug' => 'jquery-ui-button',
		'info' => 'Enhances standard form elements like buttons, inputs and anchors to themeable buttons with appropriate hover and active styles.',
		'link' => 'http://jqueryui.com/demos/button/'
	),
	'jquery-ui-datepicker' => array(
		'name' => 'Datepicker',
		'slug' => 'jquery-ui-datepicker',
		'info' => 'Select a date from a popup or inline calendar',
		'link' => 'http://jqueryui.com/demos/datepicker/'),
    'jquery-ui-dialog' => array('name' => 'Dialog',            'slug' => 'jquery-ui-dialog',            'info' => 'Open content in an interactive overlay.', 'link' => 'http://jqueryui.com/demos/dialog/'),
    'jquery-ui-menu' => array('name' => 'Menu',            'slug' => 'jquery-ui-menu',            'info' => 'Themeable menu with mouse and keyboard interactions for navigation.', 'link' => 'http://jqueryui.com/menu/'),
    'jquery-ui-progressbar' => array('name' => 'Progressbar',        'slug' => 'jquery-ui-progressbar',        'info' => 'Display status of a determinate or indeterminate process.', 'link' => 'http://jqueryui.com/demos/progressbar/'),
    'jquery-ui-selectmenu' => array('name' => 'Selectmenu',        'slug' => 'jquery-ui-selectmenu',        'info' => 'Duplicates and extends the functionality of a native HTML select element to overcome the limitations of the native control.', 'link' => 'http://jqueryui.com/selectmenu/'),
    'jquery-ui-slider' => array('name' => 'Slider',            'slug' => 'jquery-ui-slider',            'info' => 'Drag a handle to select a numeric value.', 'link' => 'http://jqueryui.com/demos/slider/'),
    'jquery-ui-spinner' => array('name' => 'Spinner',            'slug' => 'jquery-ui-spinner',            'info' => 'Enhance a text input for entering numeric values, with up/down buttons and arrow key handling.', 'link' => 'http://jqueryui.com/demos/spinner/'),
    'jquery-ui-tabs' => array('name' => 'Tabs',            'slug' => 'jquery-ui-tabs',            'info' => 'A single content area with multiple panels, each associated with a header in a list.', 'link' => 'http://jqueryui.com/demos/tabs/'),
    'jquery-ui-tooltip' => array('name' => 'Tooltips',        'slug' => 'jquery-ui-tooltip',            'info' => 'Customizable, themeable tooltips, replacing native tooltips.', 'link' => 'http://jqueryui.com/demos/tooltip/')
    ,
    'jquery-ui-widget' => array('name' => 'Widget',        'slug' => 'jquery-ui-widget',        'info' => 'Create stateful jQuery plugins using the same abstraction as all jQuery UI widgets.',    'link' => 'http://jqueryui.com/widget/'),
    'jquery-ui-position' => array('name' => 'Position',    'slug' => 'jquery-ui-position',    'info' => 'Position an element relative to the window, document, another element, or the cursor/mouse.',    'link' => 'http://jqueryui.com/demos/position/'),
    'jquery-ui-mouse' => array('name' => 'Mouse',        'slug' => 'jquery-ui-mouse',        'info' => 'Mouse Interaction'),

    'jquery-effects-blind' => array('name' => 'Blind', 'slug' => 'jquery-effects-blind'),
    'jquery-effects-bounce' => array('name' => 'Bounce', 'slug' => 'jquery-effects-bounce'),
    'jquery-effects-clip' => array('name' => 'Clip', 'slug' => 'jquery-effects-clip'),
    'jquery-effects-drop' => array('name' => 'Drop', 'slug' => 'jquery-effects-drop'),
    'jquery-effects-explode' => array('name' => 'Explode', 'slug' => 'jquery-effects-explode'),
    'jquery-effects-fade' => array('name' => 'Fade', 'slug' => 'jquery-effects-fade'),
    'jquery-effects-fold' => array('name' => 'Fold', 'slug' => 'jquery-effects-fold'),
    'jquery-effects-highlight' => array('name' => 'Highlight', 'slug' => 'jquery-effects-highlight'),
    'jquery-effects-pulsate' => array('name' => 'Pulsate', 'slug' => 'jquery-effects-pulsate'),
    'jquery-effects-scale' => array('name' => 'Scale', 'slug' => 'jquery-effects-scale'),
    'jquery-effects-shake' => array('name' => 'Shake', 'slug' => 'jquery-effects-shake'),
    'jquery-effects-slide' => array('name' => 'Slide', 'slug' => 'jquery-effects-slide'),
    'jquery-effects-transfer' => array('name' => 'Transfer', 'slug' => 'jquery-effects-transfer'),

);
