<?php

if (!defined('ABSPATH')) {
	exit;
}


$lib = array(
	'normalize' => array(
		'type' => 'style',
		'name' => 'normalize',
		'title' => 'Normalize.css',
		'src' => 'stylesheets/normalize.css',
		'ver' => '4.1.1c',
		'depend' => array(),
	),
	'justbenice' => array(
		'type' => 'style',
		'name' => 'justbenice',
		'title' => 'Justbenice.css',
		'description' => __('CSS grid from bootstrap 4 + styles needed for owlCarousel.', 'libraries'),
		'src' => 'stylesheets/justbenice.css',
		'ver' => '1.0.1',
		'depend' => array('normalize'),
	),
	'modernizr' => array(
		'type' => 'script',
		'name' => 'modernizr',
		'title' => 'Modernizr.js',
		'description' => __("Let's learn that HTML5 and CSS3 are user-friendly", 'libraries'),
		'link' => 'https://modernizr.com/',
		'src' => 'javascripts/modernizr.min.js',
		'ver' => '2.8.3',
		'depend' => array(),
	),
	'prefixfree' => array(
		'type' => 'script',
		'name' => 'prefixfree',
		'title' => 'Prefixfree.js',
		'description' => __('Eliminating the need to specify prefixes in styles.', 'libraries'),
		'link' => 'https://leaverou.github.io/prefixfree/',
		'src' => 'javascripts/prefixfree.min.js',
		'ver' => '1.0.7',
		'depend' => array(),
	),
	'pace' => array(
		'type' => 'script',
		'name' => 'pace',
		'title' => 'Pace.js',
		'description' => __('Automatic page loading indicator for the site with tracking of ajax-requests and the status of page loading (readyState).', 'libraries'),
		'link' => 'http://github.hubspot.com/pace/docs/welcome/',
		'src' => 'javascripts/pace.min.js',
		'ver' => '1.0.0',
		'depend' => array(),
	),
	'maskedinput' => array(
		'type' => 'script',
		'name' => 'maskedinput',
		'title' => 'MaskedInput.js',
		'description' => __('Allows you to do input fields with a mask.', 'libraries'),
		'link' => 'http://digitalbush.com/projects/masked-input-plugin/',
		'src' => 'javascripts/jquery/maskedinput.min.js',
		'ver' => '1.4.1',
		'depend' => array('jquery'),
	),
	'jquerymask' => array(
		'type' => 'script',
		'name' => 'jquerymask',
		'title' => 'jQueryMask.js',
		'description' => __('Allows masking text input field.', 'libraries'),
		'link' => 'http://blog.igorescobar.com',
		'src' => 'javascripts/jquery/jquery.mask.js',
		'ver' => '1.14.11',
		'depend' => array('jquery'),
	),
	'lazy' => array(
		'type' => 'script',
		'name' => 'lazy',
		'title' => 'Lazy.js',
		'description' => __('Library for progressive loading of images.', 'libraries'),
		'link' => 'http://jquery.eisbehr.de/lazy/',
		'src' => 'javascripts/jquery/jquery.lazy.min.js',
		'ver' => '1.7.5',
		'depend' => array('jquery'),
	),
	'isotope' => array(
		'type' => 'script',
		'name' => 'isotope',
		'title' => 'Isotope.js',
		'description' => __('A library for building blocks of different sizes one after another both horizontally and vertically with no spaces.', 'libraries'),
		'link' => 'http://isotope.metafizzy.co',
		'src' => 'javascripts/jquery/isotope.pkgd.min.js',
		'ver' => '3.0.1',
		'depend' => array('jquery'),
	),
	'isotope_masonry' => array(
		'type' => 'script',
		'name' => 'isotope_masonry',
		'title' => 'Masonry layout for isotope',
		'description' => __('Additional library to Isotope.js with the system of objects location.', 'libraries'),
		'link' => 'http://isotope.metafizzy.co',
		'src' => 'javascripts/jquery/isotope.masonryHorizontal.pkgd.min.js',
		'ver' => '2.0.0',
		'depend' => array('jquery','isotope'),
	),
	'isotope_cellsbyrow' => array(
		'type' => 'script',
		'name' => 'isotope_cellsbyrow',
		'title' => 'cellsByRows',
		'description' => __('cellsByRows layout mode for Isotope', 'libraries'),
		'link' => 'http://isotope.metafizzy.co/layout-modes/cellsbyrow.html',
		'src' => 'javascripts/jquery/isotope.cells-by-row.js',
		'ver' => '1.1.3',
		'depend' => array('jquery','isotope'),
	),
	'isotope_cellsbycolumn' => array(
		'type' => 'script',
		'name' => 'isotope_cellsbycolumn',
		'title' => 'cellsByColumns',
		'description' => __('cellsByColumn layout mode for Isotope', 'libraries'),
		'link' => 'http://isotope.metafizzy.co/layout-modes/cellsbycolumn.html',
		'src' => 'javascripts/jquery/isotope.cells-by-column.js',
		'ver' => '1.1.3',
		'depend' => array('jquery','isotope'),
	),
	'isotope_fitcolumns' => array(
		'type' => 'script',
		'name' => 'isotope_fitcolumns',
		'title' => 'fitColumns',
		'description' => __('fitColumns layout mode for Isotope', 'libraries'),
		'link' => 'http://isotope.metafizzy.co/layout-modes/fitcolumns.html',
		'src' => 'javascripts/jquery/isotope.fit-columns.js',
		'ver' => '1.1.3',
		'depend' => array('jquery','isotope'),
	),
	'isotope_horizontal' => array(
		'type' => 'script',
		'name' => 'isotope_horizontal',
		'title' => 'horizontal',
		'description' => __('horizontal layout mode for Isotope', 'libraries'),
		'link' => 'http://isotope.metafizzy.co/layout-modes/horiz.html',
		'src' => 'javascripts/jquery/isotope.horizontal.js',
		'ver' => '2.0.0',
		'depend' => array('jquery','isotope'),
	),
	'isotope_packery' => array(
		'type' => 'script',
		'name' => 'isotope_packery',
		'title' => 'packery',
		'description' => __('', 'libraries'),
		'src' => 'javascripts/jquery/isotope.packery-mode.pkgd.min.js',
		'ver' => '2.0.0',
		'depend' => array('jquery','isotope'),
	),
	'aspectratio' => array(
		'type' => 'script',
		'name' => 'aspectratio',
		'title' => 'aspectRatio.js',
		'description' => __('Alpha version of the library to preserve the aspect ratio for objects.', 'libraries'),
		'src' => 'javascripts/jquery/jquery.aspectratio.js',
		'ver' => '0.0.2a',
		'depend' => array('jquery'),
	),
	'stretchclass' => array(
		'type' => 'script',
		'name' => 'stretchclass',
		'title' => 'stretchClass.js',
		'description' => __('Alpha version of the library, which sets the width of the images to 100%, and the height of the auto. <br/> It takes into account the maximum width of the image from the width attribute, and if it is not set loads naturalWidth with ImagesLoaded.js', 'libraries'),
		'src' => 'javascripts/jquery/jquery.stretchclass.js',
		'ver' => '0.0.2a',
		'depend' => array('jquery','imagesloaded'),
	),
	'fullscreenclass' => array(
		'type' => 'script',
		'name' => 'fullscreenclass',
		'title' => 'fullScreenClass.js ',
		'description' => __("The Alpha version of the library, operates by opening windows on top of everything based on styles and allows an additional function of the window's properties.", 'libraries'),
		'src' => 'javascripts/jquery/jquery.fullscreenclass.js',
		'ver' => '0.0.1a',
		'depend' => array('jquery'),
	),
	'owlcarousel' => array(
		'type' => 'script',
		'name' => 'owlcarousel',
		'title' => 'owlCarousel.js',
		'description' => __('Slider for images.', 'libraries'),
		'link' => 'https://owlcarousel2.github.io/OwlCarousel2/',
		'src' => 'javascripts/jquery/owl.carousel.min.js',
		'ver' => 'v2.0.0-beta.2.4',
		'depend' => array('jquery'),
	),
	'animate' => array(
		'type' => 'style',
		'name' => 'animate',
		'title' => 'animate.css',
		'description' => __('The animation styles used by owlCarousel (can be used separately).', 'libraries'),
		'link' => 'https://daneden.github.io/animate.css/',
		'src' => 'stylesheets/animate.css',
		'ver' => '2.0.0',
		'depend' => array(),
	),
	'google_clustermarkers' => array(
		'type' => 'script',
		'name' => 'google_clustermarkers',
		'title' => 'GoogleClusterMarkers.js',
		'description' => __('A library that allows you to group markers on a map.', 'libraries'),
		'link' => 'https://github.com/googlemaps/js-marker-clusterer',
		'src' => 'javascripts/google/markerclusterer.min.js',
		'ver' => '1.0.0',
		'depend' => array('jquery','google-map'),

	),
	'google_infobubble' => array(
		'type' => 'script',
		'name' => 'google_infobubble',
		'title' => 'GoogleInfoBubble.js',
		'description' => __('Pop-ups when clicking on the marker.', 'libraries'),
		'link' => 'https://github.com/googlemaps/js-info-bubble',
		'src' => 'javascripts/google/infobubble.min.js',
		'ver' => '0.8.0',
		'depend' => array('jquery','google-map'),
	),
	'fullpage' => array(
		'type' => 'script',
		'name' => 'fullpage',
		'title' => 'Fullpage.js',
		'description' => __('Allows you to scroll page.', 'libraries'),
		'link' => 'https://github.com/alvarotrigo/fullPage.js',
		'src' => 'javascripts/jquery/jquery.fullpage.min.js',
		'ver' => '2.9.2',
		'depend' => array('jquery'),
	),
	'fullpage_scrolloverflow' => array(
		'type' => 'script',
		'name' => 'fullpage_scrolloverflow',
		'title' => 'Scrolloverflow.min.js',
		'description' => __('Scrolls everything that overflows in fullPage', 'libraries'),
		'src' => 'javascripts/jquery/scrolloverflow.min.js',
		'ver' => '5.2.0',
		'depend' => array('jquery'),
	),
	'jquery_ui_touch_punch' => array(
		'type' => 'script',
		'name' => 'jquery_ui_touch_punch',
		'title' => 'jQuery UI Touch Punch',
		'description' => __('Allows to drag manipulate elements on touch screens', 'libraries'),
		'src' => 'javascripts/jquery/jquery.ui.touch-punch.min.js',
		'ver' => '0.2.3',
		'depend' => array('jquery','jquery-ui-core','jquery-ui-widget','jquery-ui-mouse'),
	),
);


?>